### ISSUE TITLE
Error loading plugin under Ubuntu 18.04

### ISSUE THREAD

**Issue by annTull** [arjan/gnome-shell-go-to-last-workspace#10]
I tried installing the plugin through the extension's website: https://extensions.gnome.org/extension/1089/go-to-last-workspace/.
It shows me the indication that an error occurred, but it does not show me which error. When I try opening the settings window, I get this error:

> TypeError: ExtensionUtils.getSettings is not a function
> 
> Stack trace:
>   buildPrefsWidget@/home/anntull/.local/share/gnome-shell/extensions/gnome-shell-go-to-last-workspace@github.com/prefs.js:24:18
>   _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
>   @<main>:1:43

 
I then uninstalled it and tried manually installing the version 9 for GNOME 3.28 (mine is 3.28.4, to be precise). Same thing.

**Comment by arjan** [comment]
I fear your gnome shell is too old, try installing an older version, version 3 is known to work with gnome 3.28.
